### ISSUE TITLE
Last PR Broke sensor - no data shown anymore

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/authenticated#46]
**Version of the custom_component**

1.10
**Describe the bug**
Last PR 19 hours ago broke the sensor
![image](https://user-images.githubusercontent.com/36390762/61990308-58e23400-b081-11e9-9688-eaa21ecb0f87.png)

**log**
Not seeing any log entries at all

```
Add your logs here.
```

**Comment by DavidFW1960** [comment]
Reverted to 1.07 and it's working again
![image](https://user-images.githubusercontent.com/36390762/62002455-c0fb4d80-b147-11e9-99ba-17576ad30cc0.png)

**Comment by ludeeus** [comment]
@claytonjn Do you know what caused that?
I tested it in a test env, and it worked as it should there.

**Comment by nenadmilano** [comment]
Hello, same here. 1.1.0 broke the platform for me (Hassio Docker HA V0.96.5) - reverting back to 1.07 made it work again.

**Comment by claytonjn** [comment]
Working here. My initial thought is maybe it's breaking if there's nothing in the blacklist. I'll try to do some testing when I get home. 

For those that the sensor isn't working, are notifications still working?

**Comment by DavidFW1960** [comment]
I don't have a blacklist/whitelist. I am not getting any notifications either.

**Comment by ludeeus** [comment]
Just tested it in my test env, it still works there

![image](https://user-images.githubusercontent.com/15093472/62110473-c58e4600-b2ae-11e9-83c2-cad17c860797.png)

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/authenticated/releases/tag/1.1.1

**Comment by sheminasalam** [comment]
I am still getting this error even with the latest version. Any advises on how to tackle it?
